server:
  port: 8080
  servlet:
    context-path: /irma-saml-bridge
  tomcat:
    relaxed-query-chars: '<,>,[,\,],^,`,{,|,}'
    relaxed-path-chars: '<,>,[,\,],^,`,{,|,}'

version: ${project.version}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  file:
    path: